export enum UsersActionsTypes {
  GET_USERS = '[Users] GET_USERS',
  GET_USERS_SUCCESS = '[Users] GET_USERS_SUCCESS',
  GET_USERS_FAIL = '[Users] GET_USERS_FAIL',

  ADD_USER = '[Users] ADD_USER',
  ADD_USER_SUCCESS = '[Users] ADD_USER_SUCCESS',
  ADD_USER_FAIL = '[Users] ADD_USER_FAIL',

  EDIT_USER = '[Users] EDIT_USER',
  EDIT_USER_SUCCESS = '[Users] EDIT_USER_SUCCESS',
  EDIT_USER_FAIL = '[Users] EDIT_USER_FAIL',

  DELETE_USER = '[Users] DELETE_USER',
  DELETE_USER_SUCCESS = '[Users] DELETE_USER_SUCCESS',
  DELETE_USER_FAIL = '[Users] DELETE_USER_FAIL',

  UPDATE_CURRENT_USER = '[Users] UPDATE_CURRENT_USER',
  REFRESH_USER_EDD_EDIT = '[Users] REFRESH_USER_ADD_EDIT',
}
